version: '3.8'

services:
  # postgres:
  #   image: postgres:13
  #   container_name: pet_markt_postgres #this is to put en instead o the ip
  #   environment:
  #     - POSTGRES_DB=pet_markt
  #     - POSTGRES_USER=juan
  #     - POSTGRES_PASSWORD=admin123
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - /postgres_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - postgres


  # Servicio de base de datos MySQL
  mysql:
    image: mysql:5
    container_name: mysql_escolar
    environment:
      MYSQL_DATABASE: api_escolar
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Servicio phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_escolar
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - mysql

# Volúmenes persistentes
volumes:
  mysql_data:



