# version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/api_escolar?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/api_escolar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin123
#    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app/api-registro-escolar.jar"]
    entrypoint: ["./wait-for-it.sh", "db", "3306", "--", "java", "-jar", "/app/api-registro-escolar.jar"]


  db:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: api_escolar
#      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db  # 👈 el nombre del servicio, no del contenedor
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db-data:

